"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/01_image.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../../nbs/core/01_image.ipynb 4
def foo(): pass
