# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fractalart',
                'doc_host': 'https://eandreas.github.io',
                'git_url': 'https://github.com/eandreas/fractalart',
                'lib_path': 'fractalart'},
  'syms': {'fractalart.core': {'fractalart.core.foo': ('core.html#foo', 'fractalart/core.py')}}}
